spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo1?serverTimezone=GMT%2B8&useSSL=true&characterEncoding=UTF-8
    username: root
    password: root
#  thymeleaf:
#    cache: false
#    prefix: classpath:/static/
#    suffix: .html
#    encoding: UTF-8
#    content-type: text/html
#    mode: HTML5

  resources:
    static-locations:classpath:/templates/
  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates/

server:
  port: 8089

mybatis:   # 配置路径从resource下面开始就可以！！！！！
  #  typeAliasesPackage: com.neuedu.entity
  mapper-locations: classpath*:mybatis/mapper/*.xml
  #  配置
  type-aliases-package: com.project.pojo
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致
